import { Inter } from "next/font/google";
import "./globals.css";

import { Poppins } from 'next/font/google';
import { Providers } from "./providers";
import ToastComponent from "./components/ToastComponent";
import DndProviders from "./components/DndProvider";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body>
        <Providers>
          <DndProviders>
            {children}
          <ToastComponent />
          </DndProviders>
        </Providers>
      </body>
    </html>
  );
}

{/* <body className={inter.className}></body> */}