import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from 'next/font/google';
import { Providers } from "./providers";
import ToastComponent from "./components/ToastComponent";
import MyThemeProvider from "./MyThemeProvider";
import Navbar from "./components/navbar/Navbar";
import TopLoaderProgressBar from "./components/TopLoaderProgressBar";


const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Resume Builder",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`} suppressHydrationWarning>
      <body className="bg-gray-50 dark:bg-slate-900">
        
        <Providers>
        <TopLoaderProgressBar/>
          <MyThemeProvider>
              <Navbar />
              {children}
            <ToastComponent />
          </MyThemeProvider>
        </Providers>
        
      </body>
    </html>
  );
}

{/* <body className={inter.className}></body> */}