import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ToastComponent from "./components/ToastComponent";
import DndProviders from "./components/DndProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <DndProviders>
            {children}
          <ToastComponent />
          </DndProviders>
        </Providers>
      </body>
    </html>
  );
}
